# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f610d7de63139b429900d150223f84c3dea22d9c319aebcc1c906b70e0bf5b01af73f33e153fe7a0fd1588d4377e9473af60c01f7e4ecf27a6dd799f9892545d

test:
  secret_key_base: 134bc0c6e9dbcd43c90f8acaaf5622a275b88593c9ad4d189f7e120e12591c2484e0f397f8a4f6be66105b4e69600d1f2d6661de3e2284906a4e3b11acf382e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
